### ISSUE TITLE
Docs for outputting sql

### ISSUE THREAD

**Issue by sveri** [kumarshantanu/clj-liquibase#6]
Hi, 

In your description it says that one could: "generate SQL for actions". What I need is to output the sql statement as a string. Is that possible too?
If so, could you please add an example? I was walking through the API but was not able to find something fit.

EDIT: I do need this without connecting to a database (this is called offline mode in liquibase IIRC).

Thanks,
Sven

**Comment by kumarshantanu** [comment]
Some of the CLI commands allow a `-s` (or `--sql-only`) option:
https://github.com/kumarshantanu/clj-liquibase/blob/master/doc/intro.md#command-line-interface-cli-integration
This only outputs SQL statements rather than executing them. Is that what you want? If you want to use a Clojure function, it is here:
https://github.com/kumarshantanu/clj-liquibase/blob/master/src/clj_liquibase/core.clj#L396

**Comment by sveri** [comment]
Hi, sorry for the late comeback. I tried several things, but did not succed with any of them.

1. Via cli/entry
    (def ds (dbcp/make-datasource :h2 {:target :memory :database :default}))
    (def dbspec (spec/make-dbspec ds))
    (def ct-change1 (mu/! (ch/create-table "sampletable1"
                                           [[:id :int :null false :pk true :autoinc true]
                                            [:name [:varchar 40] :null false]
                                            [:gender [:char 1] :null false]])))
    (def changeset-1 ["id=1" "author=shantanu" [ct-change1]])
    (lb/defchangelog changelog-1 "example" [changeset-1])

returning this:

    (cli/entry "update" {:datasource ds :changelog changelog-1} "--sql-only")
    -- *********************************************************************
    -- Update Database Script
    -- *********************************************************************
    -- Change Log: C:\Users\sveri\.IdeaIC14\system\tmp\form-init4290330173672672967.clj
    -- Ran at: 3/30/15 9:27 PM
    -- Against: SA@jdbc:h2:mem:default
    -- Liquibase version: 3.0.8
    -- *********************************************************************
    -- Lock Database
    false @ false @ true
    INFO 3/30/15 9:27 PM:liquibase: Successfully acquired change log lock
    -- Release Database Lock
    INFO 3/30/15 9:27 PM:liquibase: Reading from PUBLIC.DATABASECHANGELOG
    INFO 3/30/15 9:27 PM:liquibase: Reading from PUBLIC.DATABASECHANGELOG
    INFO 3/30/15 9:27 PM:liquibase: Successfully released change log lock

and in the changelog I can see a lot of weird clojure code. I am not sure what is supposed to be there.

Second I tried to call change-sql directly, but I don't know how to set *db-instance* and what to. However, that did not work either. I defined my own function similar to yours:

    (defn ^List change-sql
      [^Change change ds]
      (let [sgf (SqlGeneratorFactory/getInstance)
            sql (map (fn [^SqlStatement stmt]
                       (map (fn [^Sql sql]
                              ^String (.toSql sql))
                            (.generateSql sgf stmt ds)))
                     (.generateStatements change ds))]
        (into [] (flatten sql))))

But no matter what I take for ds I always get errors of this sort:
    (change-sql ct-change1 ds)
    ClassCastException org.apache.commons.dbcp.BasicDataSource cannot be cast to liquibase.database.Database  closp-crud.core/change-sql (core.clj:50)

Or this one:
    (change-sql ct-change1 dbspec)
    ClassCastException clojure.lang.PersistentArrayMap cannot be cast to liquibase.database.Database  closp-crud.core/change-sql (core.clj:50)

I tried to go through your apis, but tbh, I just don't get a clear picture of them, you are using two different libraries regarding connection building and I just dont get it. Sorry.

Maybe you could try what I did? Or show me a different way?

Thanks,
Sven

**Comment by sveri** [comment]
Well, cannot believe that. Just after I posted it I tried to debug it and therefore restarted the repl session and all of a sudden cli/entry works and outputs the sql. I just have to find a way to parse the output somehow. 

Thanks anyway :-)

**Comment by kumarshantanu** [comment]
@sveri Is your problem solved now? You may like to close the issue if it is, or update the thread pointing out what's the problem you are still facing.

**Comment by sveri** [comment]
Yea, I finally managed to use change-sql directly as I originally wanted to. Thank you very much for your support.
